services:
  - type: web
    name: invoice-processor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: ENVIRONMENT
        value: production
    autoDeploy: true
  
  - type: web
    name: invoice-processor-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: https://invoice-processor-backend.onrender.com
    autoDeploy: true
