name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Dependencies (Main App)
      run: npm install

    - name: Build Main App
      run: npm run build

    - name: Install Dependencies (Finbot)
      working-directory: ./finbot-linguist-ai
      run: npm install

    - name: Build Finbot
      working-directory: ./finbot-linguist-ai
      run: npm run build

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install Python Dependencies (GST Assistant)
      working-directory: ./GST Assistant
      run: pip install -r requirements.txt

    - name: Install Python Dependencies (Invoice Processor)
      working-directory: ./invoice-processor/backend
      run: pip install -r requirements.txt

  deploy-production:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3

    # Deploy Main App to Vercel
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.ORG_ID }}
        vercel-project-id: ${{ secrets.PROJECT_ID }}
        working-directory: ./

    # Deploy Finbot to Render
    - name: Deploy Finbot to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST https://api.render.com/v1/services \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data-binary "@finbot-linguist-ai/render.yaml"

    # Deploy GST Assistant to Render
    - name: Deploy GST Assistant to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST https://api.render.com/v1/services \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data-binary "@GST Assistant/render.yaml"

    # Deploy Invoice Processor to Render
    - name: Deploy Invoice Processor to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST https://api.render.com/v1/services \
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          --data-binary "@invoice-processor/render.yaml"
